NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 60
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 15
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 12


NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 75
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 25.0
NDefines.NDiplomacy.BASE_STAGE_COUP_DAILY_PP = 9999
NDefines.NDiplomacy.BASE_STAGE_COUP_TOTAL_COST = 9999


NDefines.NCountry.RESISTANCE_STRENGTH_FROM_VP = 0
NDefines.NCountry.RESISTANCE_STRENGTH_FROM_UNIT = 0
NDefines.NCountry.RESISTANCE_STRENGTH_FROM_NEIGHBORS = 0
NDefines.NCountry.RESISTANCE_DECAY_WHEN_NO_GROWTH = 0

NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.10
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 24

NDefines.NCountry.STARTING_FUEL_RATIO = 0.25
NDefines.NCountry.BASE_FUEL_CAPACITY = 100000


NDefines.NProduction.MIN_LICENSE_ACTIVE_DAYS = 1

NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 15
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 30
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 10
NDefines.NProduction.MAX_MIL_FACTORIES_PER_LINE = 200


NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 40 
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 100

NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999

NDefines.NMilitary.TRAINING_ATTRITION = 0.03
NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.15
NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.3

NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.04


NDefines.NAir.COMBAT_DAMAGE_SCALE_CARRIER = 1
NDefines.NAir.NAVAL_COMBAT_EXTERNAL_PLANES_JOIN_RATIO = 0.03
NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 0.80
NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.8
NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_CHANCE = 0.1
NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 0.9
NDefines.NAir.ANTI_AIR_MAXIMUM_DAMAGE_REDUCTION_FACTOR = 0.75
NDefines.NAir.AIR_WING_BOMB_DAMAGE_FACTOR = 1

NDefines.NAir.MISSION_FUEL_COSTS = {  -- fuel cost per plane for each mission
		1.0, -- AIR_SUPERIORITY
		1.0, -- CAS		
		0.7, -- INTERCEPTION	
		1.5, -- STRATEGIC_BOMBER
		1.0, -- NAVAL_BOMBER	
		1.0, -- DROP_NUKE		
		1.0, -- PARADROP		
		0.75, -- NAVAL_KAMIKAZE	
		1.2, -- PORT_STRIKE		
		1.0, -- AIR_SUPPLY		
		0.8, -- TRAINING
		1.0, -- NAVAL_MINES_PLANTING
		1.0, -- NAVAL_MINES_SWEEPING
	}

NDefines.NAir.BOMBING_TARGETING_RANDOM_FACTOR = 0.5
NDefines.NAir.BOMBING_PROV_BUILD_PRIO_SCALE = 1
NDefines.NAir.BOMBING_STATE_BUILD_PRIO_SCALE = 1
NDefines.NAir.BOMBING_INFRA_PRIO_SCALE = 0.5


NDefines.NNavy.ADMIRAL_TASKFORCE_CAP = 15
NDefines.NNavy.CARRIER_STACK_PENALTY_EFFECT = 10.0
NDefines.NNavy.DETECTION_SUBS_CHANCE_BALANCE = 45000.0
NDefines.NNavy.CONVOY_EFFICIENCY_MIN_VALUE = 0.20
NDefines.NNavy.NAVAL_MINES_IN_REGION_MAX = 50.0